### ISSUE TITLE
Mark the new_raw function as unsafe

### ISSUE THREAD

**Issue by notgull** [rust-lang/socket2#384]
Rust may soon make it a safety requirement for sockets to always be `CLOEXEC` on Unix and `OVERLAPPED/NO_INHERIT` on Windows, see [here](https://github.com/rust-lang/rust/pull/107338). In this case, `new_raw` would need to become unsafe.

**Comment by Thomasdezeeuw** [comment]
I responded on the issue, but I don't think marking `new_raw` as `unsafe` is enough. The new documentation doesn't specify what happens if we don't follow the requirements, so I suppose it would be UB. In other words `new_raw` would no longer be possible to use at all with `Socket`, unless we change `Socket` to be a "plain" fd again.

**Comment by Thomasdezeeuw** [comment]
Per https://github.com/rust-lang/rust/pull/107338#issuecomment-1408585623 this is not needed.
